INSERT INTO artists
  (name)
VALUES
  ('Tool'),
  ('System of a Down'),
  ('Queens of the Stone Age'),
  ('A Perfect Circle'),
  ('Royal Blood'),
  ('Nothing But Thieves'),
  ('Jimmy Eat World'),
  ('Young the Giant'),
  ('White Lies'),
  ('The Killers'),
  ('Two Door Cinema Club'),
  ('The Strokes'),
  ('Interpol'),
  ('The Cinematics'),
  ('Coldplay'),
  ('The Shins'),
  ('Spoon'),
  ('The Virgins'),
  ('Radiohead'),
  ('Red Hot Chili Peppers'),
  ('Carpenter Brut'),
  ('So Below'),
  ('RÜFÜS DU SOL'),
  ('Zola Blood'),
  ('The Moth & The Flame');
