const MAX_NAME_LENGTH = 100;

export const MAX_GENRE_NAME_LENGTH = MAX_NAME_LENGTH;
export const MAX_ARTIST_NAME_LENGTH = MAX_NAME_LENGTH;
export const MAX_RECORD_NAME_LENGTH = MAX_NAME_LENGTH;

export const DEFAULT_RECORD_QUANTITY = 0;
